import { ArrowDownIcon } from '@chakra-ui/icons'
import { Divider } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo2.png" />
      </Head>

       <div style={{
        width: '100vw',
        height: '100vh',
        display: 'flex',
        overflow: 'hidden',
        flexDirection: 'column',
        
       }} >
        <Header/>
        <Divider
          orientation="horizontal"
          borderColor="gray.200"
          borderWidth="1px"


          
        />
        <Hero/>
       <div onClick={()=>alert('clicked')} style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        cursor:'pointer'
       }}>
        <Image
        src="/pics/arrrowdown.gif"
        alt="Picture of the author"
        width={150}
        height={150}

        />
       </div>
       </div>

     
    </div>
  )
}
